version: '3.9'

services:
# mongodb service
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes: 
      - mongo_db:/data/db

# node service
  api:
    build: .

